@startuml
start
:Загрузить изображение;
if (Файл валиден?) then (да)
  :Отобразить оригинал;
  fork
    :Изменить яркость/контраст;
  fork again
    :Изменить размер;
  end fork
  :Применить изменения;
  :Сохранить;
else (нет)
  :Ошибка;
endif
stop
@enduml