@startuml
left to right direction
actor "Пользователь" as User
rectangle System {
  User --> (Загрузить изображение)
  User --> (Изменить яркость)
  User --> (Изменить контраст)
  User --> (Изменить размер)
  User --> (Сохранить результат)
  User --> (Сбросить изменения)
}
@enduml